version: '2'
services:
  app:
    build: rails
    user: 1000:1000
    volumes:
      # - /app/log
      - ./work:/app
    ports:
      - '3000:3000'
    environment:
      RAILS_ENV: development
    extends:
      file: ./mysql/password.yml
      service: password
    depends_on:
      - db
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/volumes:/var/lib/mysql
    extends:
      file: ./mysql/password.yml
      service: password
  web:
    build: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
    volumes_from:
      - app
